### ISSUE TITLE
[Bug] Неправильная работа factory.load() при запуске в AsyncIOScheduler

### ISSUE THREAD

**Issue by EugeneRymarev** [reagento/adaptix#106]
Есть `scheduler = AsyncIOScheduler()`, в котором происходит получение записей из БД с последующей загрузкой в `factory.load()`.
`factory.load()` возвращает те же данные, что и были в него переданы `List[Record]`, где [Record](https://github.com/encode/databases/blob/master/databases/backends/postgres.py#L76).
Когда эта же функция выполняется в основном цикле, то обработка происходит верно.
В качестве рабочего решения было предложено использовать:
`factory.parser(List[MyModel])(records)`,
которая успешно отрабатывает в обоих loop'ах, как в основном, так и в `apscheduler.AsyncIOScheduler`

[Обсуждение](https://t.me/ru_python_beginners/1200369)

**Comment by EugeneRymarev** [comment]
`factory.parser(List[MyModel])(records)` всё же не работает.
Путём проб и ошибок выяснилось, что проблема не повторяется, если заменить
`factory.load(records, List[MyModel])`
на
`[factory.load(record, MyModel) for record in records]`

**Comment by tarrac79** [comment]
[nms.zip](https://github.com/Tishka17/dataclass_factory/files/5273571/nms.zip)
По просьбе из чата, прикрепляю свой код

**Comment by tarrac79** [comment]
[nms.zip](https://github.com/Tishka17/dataclass_factory/files/5273580/nms.zip)
По просьбе из чата
