### ISSUE TITLE
API redesign

### ISSUE THREAD

**Issue by Tishka17** [reagento/adaptix#110]
* load/dump vs parsers/serializers - fix naming
* dynamic name mapping
* "ORM mode" or custom gettersm which also required for multidict
* use one class as fields list, but create another or parse different class 
* per-field schema, not only per type
* type groups and plugin support
* splify getting parsers from schema
* other methods like jsonschema, object update, etc

**Comment by zhPavel** [comment]
We should remove support for Optional without arguments
