### ISSUE TITLE
Prepare data before passing to custom parser

### ISSUE THREAD

**Issue by Tishka17** [reagento/adaptix#19]
Custom parser can be provided in Schema. 

It is ok to parse data in dict before passing to custom parser or provide a way to call use factory inside custo mparser. 

1. Pass factory instance
2. Check custom parser anotations
3. Add zero-step parsing setting (e.g. link to other type)

**Comment by Tishka17** [comment]
Probably can be replaced with #24 and post parse step

**Comment by zhPavel** [comment]
Does not apply to the new major version, now we have chaining
