### ISSUE TITLE
dataclass <-> tuple 

### ISSUE THREAD

**Issue by Tishka17** [reagento/adaptix#20]

**Comment by Tishka17** [comment]
Как вариант: 
Если name_mapping - список, а не словарь, дампить в список.
При этом все неуказанные поля добавлять в порядке их следования в исходном классе. 

```
@dataclass
class A:
    first: int
    second: int
```


Если взять схему:
```
schema = Schema(
    name_mapping=[]
)
```
Превратит объект A(1,2) в [1,2]


Если взять схему:
```
schema = Schema(
    name_mapping=['second']
)
```
Превратит объект A(1,2) в [2,1]


Если взять схему:
```
schema = Schema(
    name_mapping=['second'],
    only_mapped=True,
)
```
Превратит объект A(1,2) в [2]



**Проблема:** нельзя сделать иерархию внутри списка как в случае с маппингом. Но возможно это и не нужно.

**Comment by Tishka17** [comment]
В текущий момент возможно сделать список из датакласса указав все необходимые поля в name_mapping в виде 
```
{
  "first": (0, ),
  "second": (1, )
}
```

**Comment by zhPavel** [comment]
Now we have mapping to list
