### ISSUE TITLE
Get form multivalue using methods like getlist

### ISSUE THREAD

**Issue by Tishka17** [reagento/adaptix#44]
In werkzeug MultiDict allows to use `getlist` to get multiple values for single name in form data.

This could be useful for filing dataclass List field

**Comment by Tishka17** [comment]
Можно запилить мапу вида

класс -> геттер и геттер секвенса.
dict: (operator.getitem, operator.getitem),
QueryDict: (QueryDict.get, QueryDict.getlist),
MultidictDict: (MultidictDict.get, MultidictDict.getlist),
Sequence: (operator.getitem, operator.getitem)

**Comment by Tishka17** [comment]
Осторожно: itemgetter медленнее чем квадратные скобки

**Comment by zhPavel** [comment]
This issue is generalized by #287
