### ISSUE TITLE
model inheritance

### ISSUE THREAD

**Issue by Tishka17** [reagento/adaptix#61]
Допустим есть классы с наследованием
```python
@dataclass
class A:
   a: int

@dataclass
class B(A):
   b: int
```

Сейчас, если мы хотим сделать предобработку поля a, мы должны сделать две схемы: для класс A и для класса B и в обеих определить pre_parse.

Необходимо продумать как это делать более удобно

**Comment by Tishka17** [comment]
Идея:

```
class ASchema(Schena):
   def pre_parse(self, data):...

class BSchema(ASchema):
   def pre_parse(self, data):
      data = super().pre_parse(data)
      ...
````

проверить, что такое допустимо и работает

**Comment by Tishka17** [comment]
Идея. Предположим меня есть два базовых датакласса и есть у них схемы, описывающие правила парсинга (какие поля парсить, предобработка и т.п.)

```python
@dataclass
class A:
    a: int
    x: str = None


@dataclass
class B:
    b: int = 0
    y: str = None

class ASchema(Schema):
    only = ["a"]
    name_style = NameStyle.snake

    def pre_parse(self, data):
        print("aschema")
        data["a"] = data["a"] * 2
        return data


class BSchema(Schema):
    only = ["b"]
    exclude = ["y"]
    def pre_parse(self, data):
        print("bschema")
        data["b"] = -data["b"]
        return data


aschema = ASchema()
bschema = BSchema()
```

Если я наследую от них обоих новый датакласс, для него никакая схема применяться не будет. 
Насколько логично иметь такой алгоритм:

1. pre_parse/post_parse/pre_serialize/post_serialize вызываются в MRO порядке
2. only, exclude, name_mapping объединяются в MRO порядке
3. прочие настройки типа name_style проверяются чтобы не противоречили друг другу. 
4. кастомные parse, serialize не должны быть заданы

То есть в данном случае будет эквивалентно:

```python
@dataclass
class C(A, B):
    pass

def c_pre_parse(self, data):
    data = aschema.pre_parse(self, data)
    data = bschema.pre_parse(self, data)
    return data


cschema = Schema(
    only = ["a", "b"],
    exclude = ["y"],
    name_style = NameStyle.snake,
    pre_parse = c_pre_parse,
)
```

**Comment by Tishka17** [comment]
Вопрос: как быть в случае когда один класс наследуется от другого, а там определен только `only`

**Comment by Tishka17** [comment]
Вопрос: два родительских класса с разными стилями имён. Имеет смысл поддержать чтобы они оба парсились корректно

**Comment by zhPavel** [comment]
This issue is not actual with the new major version
