### ISSUE TITLE
Implement update_forward_refs for delayed forward refs calculation

### ISSUE THREAD

**Issue by Tishka17** [reagento/adaptix#63]
аналогичная функциональность в Pydantic

model_a.py
```python
from pydantic import BaseModel


class ModelA(BaseModel):
    field: int
```

model_b.py
```python
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel

if TYPE_CHECKING:
    from model_a import ModelA


class ModelB(BaseModel):
    field: int
    a: ModelA
```

main.py
```python
from model_b import ModelB

print(ModelB.__fields__)
-> {'field': ModelField(name='field', type=int, required=True), 'a': ModelField(name='a', type=ForwardRef('ModelA'), required=PydanticUndefined)}
```

по `type=ForwardRef `и в этом месте неизвестно что именно из себя представляет `ModelA` для `ModelB` потому что его нет в скоупе модуля `model_b`.

для этого есть `ModelB.update_forward_refs()`
вызываем из main.py
только прямой вызов `ModelB.update_forward_refs()` ничего не сделает - `NameError: name 'ModelA' is not defined`, потому что в модуле где находится класс все еще нет такого имени

делаем следующее - `ModelB.update_forward_refs(ModelA=ModelA)`

и далее снова смотрим поля:
`{'field': ModelField(name='field', type=int, required=True), 'a': ModelField(name='a', type=ModelA, required=True)}`
`ModelA` теперь имеет реальный тип а не референс

**Comment by Tishka17** [comment]
пример чисто на датаклассах

a.py
```python
from dataclasses import dataclass
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from b import B

@dataclass
class A:
    b: Optional['B']
```
b.py
```python
from dataclasses import dataclass
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from a import A

@dataclass
class B:
    a: Optional['A']
```
main.py
```python
from b import B
from a import A

print(B(A(None)))
```

**Comment by zhPavel** [comment]
Converted to #288
