### ISSUE TITLE
Support pydantic models

### ISSUE THREAD

**Issue by Tishka17** [reagento/adaptix#89]
At least support defaults and fields list

**Comment by hyusetiawan** [comment]
turns out it's pretty straight forward to support this:
you can use the following class:
```
class ObjectFactory(Factory):
    def __init__(self, schemas: List[Any]], *args, **kwargs):
        kwargs["schemas"] = {
            schema: Schema(parser=lambda data: schema(**data),) for schema in schemas
        }
        super().__init__(*args, **kwargs)

    def dump(self, data: TypedObject) -> Dict[str, Any]:
        return data.dict()
```

**Comment by Tishka17** [comment]
Probably it's a good idea of intermediate step. But i'd like to be able to configure behavior of serializing using `Schema` instances.

**Comment by hyusetiawan** [comment]
@Tishka17 perhaps also support construct() based instantiation then?
especially for my use case, event based message passing using pydantic models, the source is trusted and i would like to bypass validation: https://pydantic-docs.helpmanual.io/usage/models/#creating-models-without-validation

**Comment by zhPavel** [comment]
New major version supports pydantic
